# -*- coding: utf-8 -*-
"""quarentenaAula1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OsiejVWXRHTxuAmFTrkM28hpQ2W9YeeS
"""

print('Hello, world!')

#importando a biblioteca pandas
import pandas as pd

#filmes é um dataframe
filmes = pd.read_csv("https://raw.githubusercontent.com/icarorodolfo/QuarentenaDeDados/master/movies.csv")

from google.colab import drive
drive.mount('/content/drive')

filmes.head()

avaliacoes = pd.read_csv("/content/drive/My Drive/Colab Notebooks/ml-latest-small/ratings.csv")

avaliacoes.head()

#Numero de linhas de avaliacoes
len(avaliacoes)

#Numero de linhas e numero de colunas
avaliacoes.shape

avaliacoes.columns = ["usuarioId", "filmeId", "nota", "momento"]

avaliacoes.head()

avaliacoes.query("filmeId==1")

avaliacoes.describe()

avaliacoes.query("filmeId==1").describe()

avaliacoes.query("filmeId==1")["nota"].mean()

avaliacoes.query("filmeId==1").mean()

avaliacoes.groupby("filmeId")

avaliacoes.groupby("filmeId").mean()

notas_medias_por_filme = avaliacoes.groupby("filmeId")["nota"].mean()

